### ISSUE TITLE
Create wikis on github.

### ISSUE THREAD

**Issue by caesarchad** [bitconch/bus#1]
10 articles on wiki

**Comment by caesarchad** [comment]
@luhuimao great work!
Please create the following entries to the wiki, if they are not created yet:
- Mutual Trust Node
- DAG
- Graph Theory
- Edge(Graph Theory)
- Transaction Validators
- Byzentine General Problem
- Zero Knowledge Proof
- Thin Client
- Smart Contract
- Bitconch Virtual Machine
- Post-Quantum Cryptography
- Side Chain
- One way/Two way pegg

https://www.microsoft.com/en-us/research/project/post-quantum-cryptography/

**Comment by luhuimao** [comment]
Ten articles related Block Chain created, bro @caesarchad

**Comment by luhuimao** [comment]
Added an new article of graph theory to wiki,  bro @caesarchad

**Comment by caesarchad** [comment]
@luhuimao  so far so good, please finish these articles by the end of this weekend

**Comment by luhuimao** [comment]
All finished bro @caesarchad

**Comment by caesarchad** [comment]
@luhuimao awesome! Thanks for your effort!! These are all high-quality articles.
