### ISSUE TITLE
MVP Test environment preparation

### ISSUE THREAD

**Issue by caesarchad** [bitconch/bus#12]
#### host 1
1 - Download all the files from /testchain/.. on master branch
2 - Download the geth from /cmd/geth/
3 - Start node00
#### host 2
1 - Download all the files from /testchain/.. on master branch
2 - Download the geth from /cmd/geth/
3 - Start node01
4 - Add peer node 
5 - modifty the app.json file 
6 - nmp start
7 - navigate to localhost:8000 to see the block explorer.

**Comment by caesarchad** [comment]
1 -  Smart Contract Deploy Suite 
-- Online : Remix IDE
-- Local : Ganache + Truffle Suite

**Comment by caesarchad** [comment]
### Test Case 1 

1.  Set up MPV in Lab environment

2.  Run nodejs script for a 100+ airdrop (transactions)


  ### Test Case 2

1.  Set up MPV in Lab environment

2.  Run script of loop transactions .

**Comment by luhuimao** [comment]
@caesarchad  Bro If failed at Parity installation and got an error likes  : ```..\src\addon.cpp(59): error C2661: “v8::Function::NewInstance”: 没有重载函数接受 2 个参数 [E:\polymath-token-15-1-18_airdrop_script\node_modules\sha3\build\sha3.vcxproj]``` ,then probably a breaking change in node10 , I uninstall node 10 then install node 8 problem solved.

**Comment by luhuimao** [comment]
There are two ways to install npm packages: locally or globally. Choose which kind of installation to use based on how you want to use the package.

- If you want to depend on the package from your own module, using something like Node.js' require, then you want to install locally. This is npm install's default behavior.
- If you want to use a package as a command line tool, then install it globally. This way, it works no matter which directory is current. This is the choice you would use if you were installing grunt, for example.

To download packages globally, use the command npm install -g <package>, e.g.:
```npm install -g jshint```

**Comment by luhuimao** [comment]
Deploy smart contract locally by Ganache CLI, I followed this [article ](https://www.jianshu.com/p/9233c214e205) and works good to me, smart contract can deployed and executed manually .
Next step I gonna to test 100+ transactions  automatically .

**Comment by caesarchad** [comment]
1. Create a folder with <whateveryoulikeTheNameIS>
2. Truffle init
3. npm init
4. npm install several pkg ( web3, etc...)
5.

**Comment by caesarchad** [comment]
Update the tracker with more details.
Test env set.
