### ISSUE TITLE
Techinical writings

### ISSUE THREAD

**Issue by caesarchad** [bitconch/bus#9]
Create 20 technical articles. And post them on medium/stemmit/hackernoon
Important:
Link github/telegram/facebook/etc at the bottom of these articles.

Topics:
Nature of blockchain's consensus algorithm
How POR will help developers build a social application on the blockchain.
What is Reputation on blockchain?
How does EVM work? 
How to build a virtual machine for the smart contract.

**Comment by luhuimao** [comment]
Bro @caesarchad  eight articles been published on Medium now, you can visit by 
[check it out](https://medium.com/@luhuimao/proof-or-reputation-as-hierarchical-reputation-consensus-d06d331adb2a_)

**Comment by luhuimao** [comment]
All done, bro @caesarchad

**Comment by caesarchad** [comment]
@luhuimao thank you for effort for medium articles, then To add a story . go to your story -> bottom right on your story there will be 3 dots ,click on them -> add to publication -> select coinmonks and submit

**Comment by luhuimao** [comment]
All of them been submitted to BITCONCH Bro @caesarchad
